version: '3'
services:
  app:
    volumes:
      - ./:/app
    image: node:10 
    working_dir: /app
    networks:
      default:
    entrypoint: "node /app/server.js"
  redis:
    image: redis 
    ports:
      - 6379:6379
    networks:
      default:
        ipv4_address: 172.42.0.24
networks:
  default:
    external:
      name: sockets-network